### ISSUE TITLE
Peer to peer Code Review

### ISSUE THREAD

**Issue by Luiscarlosvd** [romans-adi/leaderboard#3]
Hi @romans-adi!

You have done an excellent job and your code is looking good but there are some things that you can improve! 😃 

- Your code is clean and organized!
- The JavaScript file looks really nice, It's very compressed and easy to understand, congrats! 🥂 
- You can improve the organization of your files by creating a modules folder to put all your .js files that are not index.js.  👍 
- There are some issues when you are trying to add a score and doesn't get the connection to the local storage, try to display a great message to tell the user that his score was saved locally but not in the server. 😉

Keep it up and Happy coding!! 🎉🍾

**Comment by romans-adi** [comment]
Thank you for this report! 
All issues are fixed and the code is up to date.

:partying_face:
